name: Build APK
on: [push]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev
          pip install buildozer cython==0.29.33
      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses || true
      - name: Build with Buildozer
        run: |
          # 빌드 캐시를 삭제하고 깨끗한 상태에서 다시 빌드합니다.
          buildozer android clean
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PristonTale_Final_APK
          path: bin/*.apk
